apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "todo-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
