apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jobs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default

  source:
    repoURL: https://github.com/VictorB13/infra-gitops.git
    targetRevision: main
    path: jobs

  destination:
    server: https://kubernetes.default.svc
    namespace: todo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
